# -*- coding: utf-8 -*-
"""DOUBLE MODELS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lZTYzJ1b9NKsJpM9ntIgvrMlgdRkyQjZ
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
uploaded = files.upload()  # A button will appear to upload your CSV

import pandas as pd
df = pd.read_csv("CIC-Bell-DNS-EXF-2021.csv")
df.head()

df.shape

df.columns

df['label'].value_counts()

df['label'] = df['label'].map({
    'heavy_benign': 0,
    'heavy_attack': 1
})

encoder = LabelEncoder()
df['label'] = encoder.fit_transform(df['label'])

df = pd.get_dummies(df, columns=['rr_type'])

df.drop(columns=['sld', 'longest_word', 'distinct_domains',
                 'reverse_dns', 'unique_asn', 'distinct_ip',
                 'unique_ttl', 'unique_country'], inplace=True)

print(df.shape)
print(df.dtypes)

print(df.head())

X = df.drop('label', axis=1)
y = df['label']

import pandas as pd

# After preprocessing
df.to_csv("preprocessed10_dataset.csv", index=False)

print("Dataset saved successfully.")

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.dtypes

X_train = X_train.select_dtypes(include=['int64','float64'])
X_test = X_test.select_dtypes(include=['int64','float64'])

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train.shape
X_test.shape

X_train[:5]

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

rf_model.fit(X_train, y_train)

from sklearn.svm import LinearSVC

svm = LinearSVC()
svm.fit(X_train, y_train)

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

xgb = XGBClassifier()
xgb.fit(X_train, y_train)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression()
lr.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Predictions
rf_pred = rf_model.predict(X_test)
svm_pred = svm.predict(X_test)
dt_pred = dt.predict(X_test)
xgb_pred = xgb.predict(X_test)
lr_pred = lr.predict(X_test)

# Accuracy Scores
print("Random Forest Accuracy:      ", accuracy_score(y_test, rf_pred))
print("Linear SVM Accuracy:         ", accuracy_score(y_test, svm_pred))
print("Decision Tree Accuracy:      ", accuracy_score(y_test, dt_pred))
print("XGBoost Accuracy:            ", accuracy_score(y_test, xgb_pred))
print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_pred))

print("Random Forest Report")
print(classification_report(y_test, rf_pred))

print("Linear SVM Report")
print(classification_report(y_test, svm_pred))

print("Decision Tree Report")
print(classification_report(y_test, dt_pred))

print("XGBoost Report")
print(classification_report(y_test, xgb_pred))

print("Logistic Regression Report")
print(classification_report(y_test, lr_pred))

# Save column names before scaling
feature_names = X.columns.tolist()

# Then scale
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

!pip install joblib

import joblib

joblib.dump(rf_model, 'rf_model.pkl')
joblib.dump(svm, 'svm_model.pkl')
joblib.dump(dt, 'decision_tree_model.pkl')
joblib.dump(xgb, 'xgboost_model.pkl')
joblib.dump(lr, 'logistic_regression_model.pkl')

